require("dotenv").config();

const {
  DB_HOST = "",
  PORT = 4000,
  BASE_URL,
  ACCESS_SECRET_KEY,
  REFRESH_SECRET_KEY,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  SENDGRID_API_KEY,
  MAIN_EMAIL,
} = process.env;

module.exports = {
  DB_HOST,
  PORT,
  BASE_URL,
  ACCESS_SECRET_KEY,
  REFRESH_SECRET_KEY,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  SENDGRID_API_KEY,
  MAIN_EMAIL,
};
